backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /img
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blogs'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" , format: "YYYY-MM-DD", default: "YYYY-MM-DD" , required: true}
      - { label: "Draft", name: "draft", widget: "boolean", default: true }
      - { label: "Featured Image", name: "image", widget: "image" , required: true}
      - { label: "Description", name: "description", widget: "string" , required: true}
      - { label: "Categories", name: "categories", widget: "list", summary: "{{fields.category}}", field: { label: "Category", name: "category", widget: "string" } , required: true}
      - { label: "Tags", name: "tags", widget: "list", summary: "{{fields.tag}}", field: { label: "Tag", name: "tag", widget: "string" } , required: true}
       # https://github.com/decaporg/decap-cms/issues/4646
      - { label: "Type", name: "type", widget: "select", options: ["featured", "post"] , required: true}
      - { label: "Body", name: "body", widget: "markdown", hint: "Make sure to name added image as thumbnail" , required: true}